# Generated by Django 5.1.4 on 2025-01-02 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='name')),
                ('difficulty', models.CharField(editable=False, max_length=12)),
                ('cook_time', models.PositiveIntegerField(help_text='Time in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('ingredients', models.ManyToManyField(related_name='recipes', to='ingredients.ingredient')),
            ],
        ),
    ]
