# Generated by Django 5.1.4 on 2025-01-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(default='recipes/no_picture.jpg', upload_to='recipes/'),
        ),
    ]
